version: '2'
services:
  jenkins:
    build: .
    image: behring/jenkins-android:latest
    ports:
      - "8080:8080"
      - "50000:50000"
      - "5000:5000"
    volumes:
      - ~/docker/volumes/jenkins-android/jenkins_home:/var/jenkins_home
    networks:
      network0:
        aliases:
          - jenkins
  emulator:
    image: tracer0tong/android-emulator:latest
    environment:
      EMULATOR: android-22
    ports:
      - "5555"
      - "80"
      - "22"
      - "443"
      - "5037"
      - "5554"
      - "5900"
    networks:
      network0:
        aliases:
          - jenkins
  db:
    image: mysql
    volumes:
      - ~/docker/volumes/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mateline
      MYSQL_DATABASE: sonarqube
      MYSQL_USER: sonarqube
      MYSQL_PASSWORD: sonarqube
  sonarqube:
    depends_on:
      - db
    image: sonarqube:latest
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      SONARQUBE_JDBC_USERNAME: sonarqube
      SONARQUBE_JDBC_PASSWORD: sonarqube
      SONARQUBE_JDBC_URL: jdbc:mysql://db:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    networks:
      network0:
        aliases:
          - jenkins
networks:
  network0: