version: '2'
services:
  jenkins:
    build: .
    image: behring/jenkins-android:latest
    ports:
      - "8080:8080"
      - "50000:50000"
      - "5000:5000"
    volumes:
      - ~/docker/volumes/jenkins-android/jenkins_home:/var/jenkins_home
    networks:
      network0:
        aliases:
          - jenkins

  emulator:
    image: behring/android-emulator:24-armeabi-v7a
    ports:
      - "5555"
      - "80"
      - "22"
      - "443"
      - "5037"
      - "5554"
      - "5900"
    networks:
      network0:
        aliases:
          - jenkins

  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ~/docker/volumes/postgresql:/var/lib/postgresql
      - ~/docker/volumes/postgresql/data:/var/lib/postgresql/data
    networks:
      network0:
        aliases:
          - jenkins
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db/sonar
    volumes:
      - ~/docker/volumes/sonarqube/conf:/opt/sonarqube/conf
      - ~/docker/volumes/sonarqube/data:/opt/sonarqube/data
      - ~/docker/volumes/sonarqube/extensions:/opt/sonarqube/extensions
    networks:
      network0:
        aliases:
          - jenkins
networks:
  network0:
